# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dailly_Challenge_DetailSearchResult' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for Dailly_Challenge_DetailSearchResult
	pod 'DropDown', '2.3.13'
end
